apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: 605134452604.dkr.ecr.ap-south-1.amazonaws.com/application_docker_repo:latest
          ports:
            - containerPort: 5000
