---
- name: Configure kubeconfig for EKS cluster
  hosts: jenkins
  become: yes

  vars:
    aws_region: "ap-south-1"
    kubeconfig_path: "/home/ec2-user/.kube/config"

  tasks:
    - name: Extract EKS cluster name from local terraform_output.json
      set_fact:
        eks_cluster_name: "{{ lookup('file', '/mnt/d/ansible_learning/devops-project/VPC_EKS/terraform_output.json') | from_json | json_query('eks_cluster_name.value') }}"
      delegate_to: localhost

    - name: Debug extracted cluster name
      debug:
        var: eks_cluster_name
      delegate_to: localhost

    - name: Ensure .kube directory exists on remote host
      file:
        path: "{{ kubeconfig_path | dirname }}"
        state: directory
        mode: '0755'
        owner: ec2-user
        group: ec2-user

    - name: Update kubeconfig for EKS cluster on remote host
      command: >
        aws eks update-kubeconfig
        --region {{ aws_region }}
        --name {{ eks_cluster_name }}
        --kubeconfig {{ kubeconfig_path }}
      become_user: ec2-user
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
        AWS_DEFAULT_REGION: "{{ aws_region }}"
